
    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        bank_id bigint,
        id bigint generated by default as identity,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_address (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table customer_creditcard (
        address_id bigint not null,
        customer_id bigint not null
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        pincode varchar(255),
        primary key (id)
    );

    alter table if exists CreditCard 
       add constraint FKe2wqhnxpkjp87b3eyfq6gl39a 
       foreign key (bank_id) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_address 
       add constraint FK4n1t9cnxhkev5vdbedu0ao068 
       foreign key (address_id) 
       references Address;

    alter table if exists customer_address 
       add constraint FK7dy564lg4tac3m50d3ws4mhc4 
       foreign key (customer_id) 
       references Customer;

    alter table if exists customer_creditcard 
       add constraint FKt3ayxa3h262vhdbal2bldrhgt 
       foreign key (address_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;
